(* Explicit OK expectations for every active declaration in the pinned source.
   Counts include each element of list-valued scanning tests. *)
val checks : (string * int * string list) list = [
  ("test1", 1, [Subject.test1]),
  ("test2", 1, [Subject.test2]),
  ("test3", 1, [Subject.test3]),
  ("test4a", 1, [Subject.test4a]),
  ("test4b", 1, [Subject.test4b]),
  ("test4c", 1, [Subject.test4c]),
  ("test5a", 1, [Subject.test5a]),
  ("test5b", 1, [Subject.test5b]),
  ("test6a", 1, [Subject.test6a]),
  ("test6b", 1, [Subject.test6b]),
  ("test6c", 1, [Subject.test6c]),
  ("test7", 1, [Subject.test7]),
  ("test8a", 1, [Subject.test8a]),
  ("test8b", 1, [Subject.test8b]),
  ("test9", 1, [Subject.test9]),
  ("test9a", 1, [Subject.test9a]),
  ("test9b", 1, [Subject.test9b]),
  ("test9c", 1, [Subject.test9c]),
  ("test9d", 1, [Subject.test9d]),
  ("test9e", 1, [Subject.test9e]),
  ("test9f", 1, [Subject.test9f]),
  ("test9g", 1, [Subject.test9g]),
  ("test9h", 1, [Subject.test9h]),
  ("test9i", 1, [Subject.test9i]),
  ("test9j", 1, [Subject.test9j]),
  ("test10a", 1, [Subject.test10a]),
  ("test10b", 1, [Subject.test10b]),
  ("test10c", 1, [Subject.test10c]),
  ("test10d", 1, [Subject.test10d]),
  ("test10e", 1, [Subject.test10e]),
  ("test10f", 1, [Subject.test10f]),
  ("test10g", 1, [Subject.test10g]),
  ("test10h", 1, [Subject.test10h]),
  ("test10i", 1, [Subject.test10i]),
  ("test11a", 1, [Subject.test11a]),
  ("test11b", 1, [Subject.test11b]),
  ("test11c", 1, [Subject.test11c]),
  ("test11d", 1, [Subject.test11d]),
  ("test11e", 1, [Subject.test11e]),
  ("test11f", 1, [Subject.test11f]),
  ("test11g", 1, [Subject.test11g]),
  ("test11h", 1, [Subject.test11h]),
  ("test11i", 1, [Subject.test11i]),
  ("test11j", 1, [Subject.test11j]),
  ("test11k", 1, [Subject.test11k]),
  ("test12a", 1, [Subject.test12a]),
  ("test12b", 1, [Subject.test12b]),
  ("test12d", 1, [Subject.test12d]),
  ("test12e", 1, [Subject.test12e]),
  ("test13a", 1, [Subject.test13a]),
  ("test13b", 1, [Subject.test13b]),
  ("test13c", 1, [Subject.test13c]),
  ("test13d", 1, [Subject.test13d]),
  ("test13e", 1, [Subject.test13e]),
  ("test13f", 1, [Subject.test13f]),
  ("test13g", 1, [Subject.test13g]),
  ("test13h", 1, [Subject.test13h]),
  ("test13i", 1, [Subject.test13i]),
  ("test13j", 1, [Subject.test13j]),
  ("test13k", 1, [Subject.test13k]),
  ("test13l", 1, [Subject.test13l]),
  ("test13m", 1, [Subject.test13m]),
  ("test13n", 1, [Subject.test13n]),
  ("test15a", 1, [Subject.test15a]),
  ("test15b", 1, [Subject.test15b]),
  ("test15c", 1, [Subject.test15c]),
  ("test15d", 1, [Subject.test15d]),
  ("test15e", 1, [Subject.test15e]),
  ("test15f", 1, [Subject.test15f]),
  ("test15g", 1, [Subject.test15g]),
  ("test15h", 1, [Subject.test15h]),
  ("test16a", 1, [Subject.test16a]),
  ("test16b", 1, [Subject.test16b]),
  ("test16c", 1, [Subject.test16c]),
  ("test16d", 1, [Subject.test16d]),
  ("test16e", 1, [Subject.test16e]),
  ("test16f", 1, [Subject.test16f]),
  ("test16g", 1, [Subject.test16g])];
val () = List.app (fn (name, expectedCount, results) =>
  let
    val () = if length results = expectedCount then ()
      else raise Fail ("array." ^ name ^ ": wrong assertion count")
    fun check ([], _) = ()
      | check (result :: rest, index) =
          if result = "OK" then check (rest, index + 1)
          else raise Fail ("array." ^ name ^ "[" ^ Int.toString index ^
            "]: expected OK, got " ^ result)
  in check (results, 0) end) checks;
