(* Explicit OK expectations for every active declaration in the pinned source.
   Counts include each element of list-valued scanning tests. *)
val checks : (string * int * string list) list = [
  ("test1a", 1, [Subject.test1a]),
  ("test1b", 1, [Subject.test1b]),
  ("test1c", 1, [Subject.test1c]),
  ("test1d", 1, [Subject.test1d]),
  ("test1e", 1, [Subject.test1e]),
  ("test1f", 1, [Subject.test1f]),
  ("test1g", 1, [Subject.test1g]),
  ("test1h", 1, [Subject.test1h]),
  ("test2a", 1, [Subject.test2a]),
  ("test2b", 1, [Subject.test2b]),
  ("test2c", 1, [Subject.test2c]),
  ("test3a", 1, [Subject.test3a]),
  ("test3b", 1, [Subject.test3b]),
  ("test3c", 1, [Subject.test3c]),
  ("test4", 1, [Subject.test4]),
  ("test5a", 1, [Subject.test5a]),
  ("test5b", 1, [Subject.test5b]),
  ("test6", 1, [Subject.test6]),
  ("test7", 1, [Subject.test7]),
  ("test8a", 1, [Subject.test8a]),
  ("test8b", 1, [Subject.test8b]),
  ("test8c", 1, [Subject.test8c]),
  ("test8d", 1, [Subject.test8d]),
  ("test8e", 1, [Subject.test8e]),
  ("test8f", 1, [Subject.test8f]),
  ("test9a", 1, [Subject.test9a]),
  ("test9b", 1, [Subject.test9b]),
  ("test9c", 1, [Subject.test9c]),
  ("test9d", 1, [Subject.test9d]),
  ("test9e", 1, [Subject.test9e]),
  ("test9f", 1, [Subject.test9f]),
  ("test9g", 1, [Subject.test9g]),
  ("test9h", 1, [Subject.test9h]),
  ("test12", 1, [Subject.test12]),
  ("test13", 1, [Subject.test13]),
  ("test14", 1, [Subject.test14]),
  ("test15", 1, [Subject.test15]),
  ("test16", 1, [Subject.test16]),
  ("test17", 1, [Subject.test17]),
  ("test18", 1, [Subject.test18]),
  ("test19", 1, [Subject.test19]),
  ("test20", 1, [Subject.test20]),
  ("test21", 1, [Subject.test21]),
  ("test22a", 1, [Subject.test22a]),
  ("test22b", 1, [Subject.test22b]),
  ("test23", 1, [Subject.test23]),
  ("test24", 1, [Subject.test24]),
  ("test25", 1, [Subject.test25]),
  ("test26a", 1, [Subject.test26a]),
  ("test26b", 1, [Subject.test26b]),
  ("test27a", 1, [Subject.test27a]),
  ("test27b", 1, [Subject.test27b]),
  ("test28", 1, [Subject.test28]),
  ("test29a", 1, [Subject.test29a]),
  ("test29b", 1, [Subject.test29b]),
  ("test29c", 1, [Subject.test29c]),
  ("test30a", 1, [Subject.test30a]),
  ("test30b", 1, [Subject.test30b]),
  ("test30c", 1, [Subject.test30c]),
  ("test30d", 1, [Subject.test30d]),
  ("test30e", 1, [Subject.test30e]),
  ("test30f", 1, [Subject.test30f]),
  ("test31", 1, [Subject.test31]),
  ("test32a", 1, [Subject.test32a]),
  ("test32b", 1, [Subject.test32b]),
  ("test32c", 1, [Subject.test32c]),
  ("test32d", 1, [Subject.test32d]),
  ("test32e", 1, [Subject.test32e])];
val () = List.app (fn (name, expectedCount, results) =>
  let
    val () = if length results = expectedCount then ()
      else raise Fail ("substring." ^ name ^ ": wrong assertion count")
    fun check ([], _) = ()
      | check (result :: rest, index) =
          if result = "OK" then check (rest, index + 1)
          else raise Fail ("substring." ^ name ^ "[" ^ Int.toString index ^
            "]: expected OK, got " ^ result)
  in check (results, 0) end) checks;
