(* Explicit expectations for the pinned upstream semantic tests. *)
val checks : (string * string) list = [
  ("test1", Subject.test1),
  ("test2", Subject.test2),
  ("test3", Subject.test3),
  ("test4", Subject.test4),
  ("test5", Subject.test5),
  ("test6", Subject.test6),
  ("test7", Subject.test7),
  ("test8", Subject.test8),
  ("test9", Subject.test9),
  ("test10", Subject.test10),
  ("test11", Subject.test11),
  ("test12", Subject.test12),
  ("test13", Subject.test13),
  ("test14", Subject.test14),
  ("test15", Subject.test15),
  ("test16", Subject.test16),
  ("test17", Subject.test17),
  ("test18", Subject.test18),
  ("test19", Subject.test19),
  ("test20", Subject.test20),
  ("test21", Subject.test21),
  ("test22", Subject.test22),
  ("test23", Subject.test23),
  ("test24", Subject.test24),
  ("test25", Subject.test25),
  ("test26", Subject.test26),
  ("test27", Subject.test27),
  ("test28", Subject.test28),
  ("test29", Subject.test29),
  ("test30", Subject.test30),
  ("test31", Subject.test31),
  ("test32", Subject.test32),
  ("test33", Subject.test33),
  ("test34", Subject.test34),
  ("test35a", Subject.test35a),
  ("test35b", Subject.test35b),
  ("test35c", Subject.test35c),
  ("test36a", Subject.test36a),
  ("test36b", Subject.test36b),
  ("test36c", Subject.test36c),
  ("test37a", Subject.test37a)];
val () = List.app (fn (name, result) => if result = "OK" then () else
  raise Fail ("list." ^ name ^ ": expected OK, got " ^ result)) checks;
