(* Explicit expectations for the pinned upstream semantic tests. *)
val checks : (string * string) list = [
  ("test1", Subject.test1),
  ("test2", Subject.test2),
  ("test3", Subject.test3),
  ("test4", Subject.test4),
  ("test5", Subject.test5),
  ("test6", Subject.test6),
  ("test7", Subject.test7),
  ("test8", Subject.test8),
  ("test9", Subject.test9),
  ("test10", Subject.test10),
  ("test11a", Subject.test11a),
  ("test11b", Subject.test11b),
  ("test11c", Subject.test11c),
  ("test11d", Subject.test11d),
  ("test11e", Subject.test11e),
  ("test11f", Subject.test11f),
  ("test11g", Subject.test11g),
  ("test11h", Subject.test11h),
  ("test12a", Subject.test12a),
  ("test12b", Subject.test12b),
  ("test12c", Subject.test12c),
  ("test12d", Subject.test12d),
  ("test12e", Subject.test12e),
  ("test12f", Subject.test12f),
  ("test12g", Subject.test12g),
  ("test13a", Subject.test13a),
  ("test13b", Subject.test13b),
  ("test14", Subject.test14),
  ("test15", Subject.test15),
  ("test16a", Subject.test16a),
  ("test16b", Subject.test16b),
  ("test17", Subject.test17),
  ("test18", Subject.test18),
  ("test19", Subject.test19),
  ("test20", Subject.test20),
  ("test21", Subject.test21),
  ("test22", Subject.test22),
  ("test23", Subject.test23),
  ("test24", Subject.test24),
  ("test25", Subject.test25)];
val () = List.app (fn (name, result) => if result = "OK" then () else
  raise Fail ("string." ^ name ^ ": expected OK, got " ^ result)) checks;
