(* Explicit expectations for the pinned upstream semantic tests. *)
val checks : (string * string) list = [
  ("test1", Subject.test1),
  ("test2", Subject.test2),
  ("test3", Subject.test3),
  ("test4a", Subject.test4a),
  ("test4b", Subject.test4b),
  ("test4c", Subject.test4c),
  ("test5", Subject.test5),
  ("test6a", Subject.test6a),
  ("test6b", Subject.test6b),
  ("test6c", Subject.test6c),
  ("test7", Subject.test7),
  ("test8", Subject.test8),
  ("test9", Subject.test9),
  ("test9a", Subject.test9a),
  ("test9b", Subject.test9b),
  ("test9c", Subject.test9c),
  ("test9d", Subject.test9d),
  ("test9e", Subject.test9e),
  ("test9f", Subject.test9f),
  ("test9g", Subject.test9g),
  ("test9h", Subject.test9h),
  ("test9i", Subject.test9i),
  ("test10a", Subject.test10a),
  ("test11a", Subject.test11a),
  ("test11b", Subject.test11b),
  ("test11c", Subject.test11c),
  ("test11d", Subject.test11d),
  ("test11e", Subject.test11e),
  ("test11f", Subject.test11f),
  ("test11g", Subject.test11g),
  ("test11h", Subject.test11h),
  ("test11i", Subject.test11i)];
val () = List.app (fn (name, result) => if result = "OK" then () else
  raise Fail ("vector." ^ name ^ ": expected OK, got " ^ result)) checks;
